### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by asdptkt** [gjbae1212/fluent-bit-pubsub#2]
I am using this configuration:

```
[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    info

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name cpu
    Tag  cpu.local
    Interval Sec
    # ====
    # Read interval (sec) Default: 1
    Interval_Sec 1

# [OUTPUT]
    # Name  stdout
    # Match *

[OUTPUT]
    Name pubsub
    Match *
    Project someproject
    Topic sometopic
    Jwtpath /etc/td-agent-bit/key.json
    Debug true


```

And this is what I get:

```
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]: [] 2019-10-01 08:48:56.000236321 +0000 UTC cpu0.p_cpu 8
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]: panic: interface conversion: interface {} is float64, not []uint8
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]: goroutine 17 [running, locked to thread]:
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]: main.FLBPluginFlush(0x7f7424315700, 0xc0000001f4, 0x7f7424218070, 0x7f7423913780)
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]:         /go/pubsub/output_pubsub.go:165 +0x6ff
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]: main._cgoexpwrap_d1415491cd31_FLBPluginFlush(0x7f7424315700, 0x1f4, 0x7f7424218070, 0x55b4c2174851)
Oct 01 08:49:00 fluentbit-pubsub td-agent-bit[5097]:         _cgo_gotypes.go:88 +0x3f
```

I think you need to make sure the data type of the value before type asserting them. What do you think?

@gjbae1212

**Comment by adonley** [comment]
getting the same issue when building into fluentbit container:
`[2020/01/17 21:39:16] [ info] [sp] stream processor started
[] 2020-01-17 18:52:20.691187262 +0000 UTC kubernetes map[container_name:[100 97 116 97 100 111 103 45 97 103 101 110 116] docker_id:[97 49 99 100 100 101 53 56 102 57 102 55 57 48 53 49 99 99 49 50 55 100 55 52 102 49 57 53 52 99 102 101 98 51 54 97 52 102 51 57 101 52 98 99 55 48 99 98 57 98 97 48 49 101 53 100 51 57 52 101 53 99 51 51] namespace_name:[100 97 116 97 100 111 103] pod_name:[100 97 116 97 100 111 103 45 97 103 101 110 116 45 98 109 114 116 102]] 
panic: interface conversion: interface {} is map[interface {}]interface {}, not []uint8

goroutine 17 [running, locked to thread]:
main.FLBPluginFlush(0x7febcad10f80, 0xc00005b2ef, 0x7febd6036740, 0x7febd57136c0)
	/go/fluent-bit-pubsub/output_pubsub.go:165 +0x6ff
main._cgoexpwrap_d1415491cd31_FLBPluginFlush(0x7febcad10f80, 0x303268d90005b2ef, 0x7febd6036740, 0x55cc8aa1d0be)
	_cgo_gotypes.go:88 +0x3f`

**Comment by gjbae1212** [comment]
Thank you. 
I have lately watched this issue.
I have assumed line by line data must be string or []byte.
Fix this issue. 
Of course, all of the case doesn't take care of it.
